---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: webserver-app-dev
    app.kubernetes.io/part-of: webserver-app
    environment: development
spec:
  project: webserver-app
  source:
    repoURL: https://github.com/vigregus/webserver-app-infra.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: webserver-app-prod
    app.kubernetes.io/part-of: webserver-app
    environment: production
spec:
  project: webserver-app
  source:
    repoURL: https://github.com/vigregus/webserver-app-infra.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
