apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: webserver-app-root
    app.kubernetes.io/part-of: webserver-app
spec:
  project: webserver-app
  source:
    repoURL: https://github.com/vigregus/webserver-app-infra.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
