{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  labels:
    {{- include "webserver-app.labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "{{ .Values.imagePullSecret.reflectFrom }}"
type: kubernetes.io/dockerconfigjson
{{- end }}
