apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: infra-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.36.8
    chart: argo-rollouts
    helm:
      valueFiles:
        - rollouts-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
