---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-watcher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    repoURL: https://github.com/vigregus/webserver-app-infra.git
    targetRevision: main
    path: gitops/3-apps/frontend
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: webserver-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 1
