apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - list:
        elements:
          - environment: dev
          - environment: stage
  template:
    metadata:
      name: '{{environment}}-external-secrets'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/vigregus/webserver-app-infra.git
        targetRevision: main
        path: gitops/external-secrets
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
