apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: "0.53.0"
    helm:
      releaseName: fluent-bit
      values: |
        kind: DaemonSet
        serviceMonitor:
          enabled: true   # тоже сконвертируется в VMServiceScrape
        config:
          service: |
            [SERVICE]
                Flush     1
                Daemon    Off
                Log_Level info
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port  2020
          # tail + kubernetes фильтр как раньше
          inputs: |
            [INPUT]
                Name              tail
                Path              /var/log/containers/*.log
                Parser            cri
                Tag               kube.*
                Mem_Buf_Limit     50MB
                Skip_Long_Lines   On
          filters: |
            [FILTER]
                Name                kubernetes
                Match               kube.*
                Kube_Tag_Prefix     kube.var.log.containers.
                Merge_Log           On
                Keep_Log            Off
          outputs: |
            [OUTPUT]
                Name              loki
                Match             *
                Url               http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
                Labels            job=fluent-bit, namespace=$kubernetes['namespace_name'], pod=$kubernetes['pod_name'], container=$kubernetes['container_name']
                Line_Format       json
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true" ]
