apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infra-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.2
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: true
          defaultDashboardsEnabled: true
          service:
            type: ClusterIP
          adminUser: admin
          adminPassword: admin
          ingress:
            enabled: false
            ingressClassName: nginx
            hosts:
              - grafana.local
            path: /
            pathType: Prefix
          sidecar:
            datasources:
              enabled: true
              defaultDatasourceEnabled: true
            dashboards:
              enabled: true
              label: grafana_dashboard
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki:3100

        prometheus:
          enabled: true
          service:
            type: ClusterIP

        prometheusOperator:
          enabled: true
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false

        alertmanager:
          enabled: true
          enabled: true

        crds:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
