grafana:
  enabled: true
  defaultDashboardsEnabled: true
  service:
    type: ClusterIP
  adminUser: admin
  adminPassword: admin

prometheus:
  service:
    type: ClusterIP

prometheusOperator:
  enabled: true

alertmanager:
  enabled: true
