apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.41.1"                # можно зафиксировать версию
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1

        loki:
          schemaConfig:
            configs:
              - from: "2020-10-24"
                store: boltdb-shipper
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h

          storage_config:
            filesystem:
              directory: /var/loki/chunks
            boltdb_shipper:
              active_index_directory: /var/loki/index
              cache_location: /var/loki/index-cache
              shared_store: filesystem

        resources:
          requests: { cpu: 50m, memory: 128Mi }
          limits:   { cpu: 200m, memory: 256Mi }

        monitoring:
          serviceMonitor:
            enabled: true

        # остальные роли выключены как выше
        read: { replicas: 0 }
        write: { replicas: 0 }
        backend: { replicas: 0 }
        gateway: { replicas: 0 }
        indexGateway: { enabled: false }
        ruler: { enabled: false }
        compactor: { enabled: false }
        distributor: { enabled: false }
        querier: { enabled: 0 }
        queryFrontend: { enabled: 0 }
        ingester: { enabled: 0 }
        tableManager: { enabled: 0 }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true", "ServerSideApply=true" ]
