apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: infra-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.5
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          schemaConfig:
            configs:
              - from: 2023-01-01
                store: boltdb-shipper
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          ruler:
            storage:
              type: local
              local:
                directory: /var/loki/rules
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
        service:
          type: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
