apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.41.1"
    helm:
      releaseName: loki
      # ВАЖНО: Все строки ниже имеют нулевой отступ относительно |
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1

          # Настройки безопасности для Minikube/emptyDir
          podSecurityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true

          # Используем временный том узла (emptyDir)
          extraVolumes:
            - name: loki-data
              emptyDir: {}
          extraVolumeMounts:
            - name: loki-data
              mountPath: /var/loki

          # Init-контейнер для гарантированного исправления прав доступа
          extraInitContainers:
            - name: fix-perms
              image: busybox:1.36
              command: ["sh","-c","mkdir -p /var/loki/chunks /var/loki/index/locks && chown -R 10001:10001 /var/loki"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: loki-data
                  mountPath: /var/loki

        # Отключаем PVC
        persistence:
          enabled: false

        monitoring:
          serviceMonitor:
            enabled: true

        loki:
          # --- ИСПРАВЛЕНИЕ ОШИБКИ SCHEMA_CONFIG ---
          useTestSchema: true
          # ---------------------------------------

          memberlistConfig:
            join_members: []

          storage:
            use_thanos_objstore: false
            bucketNames: { chunks: chunks, ruler: ruler, admin: admin }

          # Конфиг самого Loki
          structuredConfig:
            auth_enabled: false
            server:
              http_listen_port: 3100

            memberlist:
              join_members: []

            ingester:
              chunk_idle_period: 5m
              chunk_retain_period: 30s
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore: { store: inmemory }
                  replication_factor: 1
                final_sleep: 0s

            # Локальное хранение (используется вместе с useTestSchema)
            storage_config:
              filesystem:
                directory: /var/loki/chunks
              boltdb:
                directory: /var/loki/index

        # Отключение всех лишних компонентов
        read:          { replicas: 0 }
        write:         { replicas: 0 }
        backend:       { replicas: 0 }
        gateway:       { enabled: false }
        distributor:   { enabled: false }
        ingester:      { enabled: false }
        querier:       { enabled: false }
        queryFrontend: { enabled: false }
        compactor:     { enabled: false }
        ruler:         { enabled: false }
        indexGateway:  { enabled: false }
        tableManager:  { enabled: false }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
