apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.41.1" # Используйте актуальную стабильную версию
    helm:
      releaseName: loki
      # Весь блок ниже - это содержимое values.yaml, переданное напрямую.
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1

          # Настройки безопасности для Minikube/emptyDir
          podSecurityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true

          # Определение временного тома
          extraVolumes:
            - name: loki-data
              emptyDir: {}

          # --- КРИТИЧЕСКОЕ ИСПРАВЛЕНИЕ: ВОЗВРАТ МОНТИРОВАНИЯ ТОМА ---
          # Этот блок необходим, чтобы основной контейнер Loki монтировал /var/loki
          # как том emptyDir, а не пытался писать в read-only файловую систему образа.
          extraVolumeMounts:
            - name: loki-data
              mountPath: /var/loki
          # -------------------------------------------------------------

          # Init-контейнер для исправления прав доступа (PERMISSION DENIED FIX)
          extraInitContainers:
            - name: fix-perms
              image: busybox:1.36
              # Создаем необходимые папки и устанавливаем владельца 10001:10001
              command: ["sh","-c","mkdir -p /var/loki/chunks /var/loki/index/locks && chown -R 10001:10001 /var/loki"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: loki-data
                  mountPath: /var/loki

        # Отключаем PersistentVolumeClaim
        persistence:
          enabled: false

        monitoring:
          serviceMonitor:
            enabled: true

        loki:
          memberlistConfig:
            join_members: []

          storage:
            use_thanos_objstore: false
            bucketNames: { chunks: chunks, ruler: ruler, admin: admin }

          structuredConfig:
            auth_enabled: false
            server:
              http_listen_port: 3100

            # --- ИСПРАВЛЕНИЕ 1: Отключение Structured Metadata ---
            limits_config:
              # Устраняет ошибку требования v13 и tsdb
              allow_structured_metadata: false
            # ----------------------------------------------------

            memberlist:
              join_members: []

            ingester:
              chunk_idle_period: 5m
              chunk_retain_period: 30s
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore: { store: inmemory }
                  replication_factor: 1
                final_sleep: 0s

            # --- ИСПРАВЛЕНИЕ 2: Явный SCHEMA_CONFIG (для прохождения валидации) ---
            schema_config:
              configs:
                - from: 2023-01-01
                  store: boltdb
                  object_store: filesystem
                  schema: v12
                  index:
                    prefix: index_
                    period: 24h
            # --------------------------------------------------------------------

            storage_config:
              filesystem:
                directory: /var/loki/chunks
              boltdb:
                directory: /var/loki/index

        # Отключение всех лишних компонентов
        read:          { replicas: 0 }
        write:         { replicas: 0 }
        backend:       { replicas: 0 }
        gateway:       { enabled: false }
        distributor:   { enabled: false }
        ingester:      { enabled: false }
        querier:       { enabled: false }
        queryFrontend: { enabled: false }
        compactor:     { enabled: false }
        ruler:         { enabled: false }
        indexGateway:  { enabled: false }
        tableManager:  { enabled: false }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
