apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.41.1" # Use current stable version
    helm:
      releaseName: loki
      # The entire block below is the contents of values.yaml passed directly.
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1

          # Security settings for Minikube/emptyDir
          podSecurityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true

          # Definition of temporary volume
          extraVolumes:
            - name: loki-data
              emptyDir: {}

          # --- CRITICAL FIX: RESTORE VOLUME MOUNTING ---
          # This block is necessary so that the main Loki container mounts /var/loki
          # as an emptyDir volume, rather than trying to write to the read-only filesystem of the image.
          # extraVolumeMounts:
          #   - name: loki-data
          #     mountPath: /var/loki
          # -------------------------------------------------------------

          # Init container for fixing access rights (PERMISSION DENIED FIX)
          extraInitContainers:
            - name: fix-perms
              image: busybox:1.36
              # Create necessary folders and set owner 10001:10001
              command: ["sh","-c","mkdir -p /var/loki/chunks /var/loki/index/locks && chown -R 10001:10001 /var/loki"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: loki-data
                  mountPath: /var/loki

        # Disable PersistentVolumeClaim
        persistence:
          enabled: false

        monitoring:
          serviceMonitor:
            enabled: true

        loki:
          memberlistConfig:
            join_members: []

          storage:
            use_thanos_objstore: false
            bucketNames: { chunks: chunks, ruler: ruler, admin: admin }

          structuredConfig:
            auth_enabled: false
            server:
              http_listen_port: 3100

            # --- FIX 1: Disable Structured Metadata ---
            limits_config:
              # Eliminates v13 and tsdb requirement error
              allow_structured_metadata: false
            # ----------------------------------------------------

            memberlist:
              join_members: []

            ingester:
              chunk_idle_period: 5m
              chunk_retain_period: 30s
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore: { store: inmemory }
                  replication_factor: 1
                final_sleep: 0s

            # --- FIX 2: Explicit SCHEMA_CONFIG (for validation) ---
            schema_config:
              configs:
                - from: 2023-01-01
                  store: boltdb
                  object_store: filesystem
                  schema: v12
                  index:
                    prefix: index_
                    period: 24h
            # --------------------------------------------------------------------

            storage_config:
              filesystem:
                directory: /var/loki/chunks
              boltdb:
                directory: /var/loki/index

        # Disable all unnecessary components
        read:          { replicas: 0 }
        write:         { replicas: 0 }
        backend:       { replicas: 0 }
        gateway:       { enabled: false }
        distributor:   { enabled: false }
        ingester:      { enabled: false }
        querier:       { enabled: false }
        queryFrontend: { enabled: false }
        compactor:     { enabled: false }
        ruler:         { enabled: false }
        indexGateway:  { enabled: false }
        tableManager:  { enabled: false }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
