apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.41.1"
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1

          # Исправляем права доступа
          podSecurityContext:
            fsGroup: 10001
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true

        # Отключаем PVC для Minikube
        persistence:
          enabled: false

        monitoring:
          serviceMonitor:
            enabled: true

        loki:
          structuredConfig:
            auth_enabled: false
            server:
              http_listen_port: 3100

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
