apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.41.1"
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1
          resources:
            requests: { cpu: 50m,  memory: 128Mi }
            limits:   { cpu: 200m, memory: 256Mi }

          podSecurityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch
          containerSecurityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false

          # Монтируем ВСТРОЕННЫЙ volume `storage` ДОПОЛНИТЕЛЬНО в /data
          extraVolumeMounts:
            - name: storage        # это встроенный volume чарта
              mountPath: /data

          # Чиним права именно в /data (это тот же volume `storage`)
          extraInitContainers:
            - name: fix-perms
              image: busybox:1.36
              securityContext:
                runAsUser: 0
              command: ["/bin/sh", "-c"]
              args:
                - >
                  mkdir -p /data/chunks /data/index &&
                  chown -R 10001:10001 /data &&
                  chmod -R g+rwX /data
              volumeMounts:
                - name: storage
                  mountPath: /data

        # Оставляем встроенный emptyDir (без PVC)
        persistence:
          enabled: false

        monitoring:
          serviceMonitor:
            enabled: true

        # На всякий случай обнулим scalable-роли
        read:          { replicas: 0 }
        write:         { replicas: 0 }
        backend:       { replicas: 0 }
        gateway:       { replicas: 0 }
        distributor:   { enabled: false }
        ingester:      { enabled: false }
        querier:       { enabled: false }
        queryFrontend: { enabled: false }
        compactor:     { enabled: false }
        ruler:         { enabled: false }
        indexGateway:  { enabled: false }
        tableManager:  { enabled: false }

        loki:
          useTestSchema: true
          storage:
            use_thanos_objstore: false
            bucketNames: { chunks: chunks, ruler: ruler, admin: admin }
          memberlistConfig:
            join_members: []

          # РЕАЛЬНЫЙ runtime-конфиг: пути указываем в /data
          structuredConfig:
            auth_enabled: false
            server:
              http_listen_port: 3100
            memberlist:
              join_members: []

            ingester:
              chunk_idle_period: 5m
              chunk_retain_period: 30s
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore: { store: inmemory }
                  replication_factor: 1
                final_sleep: 0s

            storage_config:
              filesystem: { directory: /data/chunks }
              boltdb:     { directory: /data/index }


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
