apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.41.1"
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1

          # Security settings for Minikube/emptyDir
          podSecurityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true

          # Override the default volume with our emptyDir
          extraVolumes:
            - name: loki-data
              emptyDir: {}

          # Override the default volume mount to use our emptyDir volume
          extraVolumeMounts:
            - name: loki-data
              mountPath: /var/loki

          # Init container for fixing access rights
          extraInitContainers:
            - name: fix-perms
              image: busybox:1.36
              command: ["sh","-c","mkdir -p /var/loki/chunks /var/loki/index/locks && chown -R 10001:10001 /var/loki"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: loki-data
                  mountPath: /var/loki

        # Disable PersistentVolumeClaim
        persistence:
          enabled: false

        # Override the default volume configuration
        volumes:
          - name: loki-data
            emptyDir: {}

        volumeMounts:
          - name: loki-data
            mountPath: /var/loki

        monitoring:
          serviceMonitor:
            enabled: true

        loki:
          memberlistConfig:
            join_members: []

          storage:
            use_thanos_objstore: false
            bucketNames: { chunks: chunks, ruler: ruler, admin: admin }

          structuredConfig:
            auth_enabled: false
            server:
              http_listen_port: 3100

            limits_config:
              allow_structured_metadata: false

            memberlist:
              join_members: []

            ingester:
              chunk_idle_period: 5m
              chunk_retain_period: 30s
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore: { store: inmemory }
                  replication_factor: 1
                final_sleep: 0s

            schema_config:
              configs:
                - from: 2023-01-01
                  store: boltdb
                  object_store: filesystem
                  schema: v12
                  index:
                    prefix: index_
                    period: 24h

            storage_config:
              filesystem:
                directory: /var/loki/chunks
              boltdb:
                directory: /var/loki/index

        # Disable all unnecessary components
        read:          { replicas: 0 }
        write:         { replicas: 0 }
        backend:       { replicas: 0 }
        gateway:       { enabled: false }
        distributor:   { enabled: false }
        ingester:      { enabled: false }
        querier:       { enabled: false }
        queryFrontend: { enabled: false }
        compactor:     { enabled: false }
        ruler:         { enabled: false }
        indexGateway:  { enabled: false }
        tableManager:  { enabled: false }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
