apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-k8s-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-metrics-k8s-stack
    targetRevision: "0.59.3"
    helm:
      releaseName: vm-stack
      values: |
        grafana:
          enabled: true
          # Настраиваем источники данных Графаны (синтаксис чарта grafana)
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: VictoriaMetrics
                  type: prometheus
                  access: proxy
                  url: http://vmsingle-vm-stack.monitoring.svc.cluster.local:8428
                - name: Loki
                  type: loki
                  access: proxy
                  url: http://loki.logging.svc.cluster.local:3100
        # базовые настройки сборщика
        vmagent:
          enabled: true
          spec:
            scrapeInterval: 30s
        vmalert:
          enabled: true
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true" ]
