apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vigregus/webserver-app-infra.git
    targetRevision: main
    path: gitops
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
