apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      backend=ghcr.io/vigregus/webserver-app-back,
      frontend=ghcr.io/vigregus/webserver-app-front
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/update-strategy: newest-build
    argocd-image-updater.argoproj.io/allow-tags: regexp:^[0-9]+\.[0-9]+.*$
    argocd-image-updater.argoproj.io/git-commit-message: |
      Update {{.AppName}} to {{range .Images}}{{.Name}}:{{.Tag}} {{end}}
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:argocd/ghcr-secret#username#password
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/ghcr-secret#username#password
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: webserver-apps
  source:
    repoURL: https://github.com/vigregus/webserver-app-infra.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
