helm:
  parameters:
    - name: backend.image.repository
      value: ghcr.io/vigregus/webserver-app-back
      forcestring: true
    - name: frontend.image.repository
      value: ghcr.io/vigregus/webserver-app-front
      forcestring: true
