# Global settings
global:
  imageRegistry: "ghcr.io/vigregus"
  imagePullSecrets:
    - name: ghcr-secret
  storageClass: ""

# Backend service configuration
backend:
  enabled: true
  name: backend

  image:
    repository: ghcr.io/vigregus/webserver-app-back
    tag: "1.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

  replicaCount: 1

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # Environment variables
  env:
    - name: PORT
      value: "8000"
    - name: PYTHONUNBUFFERED
      value: "1"

  # Health check configuration
  healthCheck:
    enabled: true
    path: "/health"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  config:
    apiUrl: "http://webserver-app-backend:8000"
    version: "1.0.0"
    environment: "production"
    features:
      metrics: true
      cors: true
      rateLimit: false
    limits:
      maxUsers: 1000
      maxAge: 120

# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: webserver-app.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
  tls: []
  #  - secretName: webserver-app-tls
  #    hosts:
  #      - webserver-app.local

# Service configuration
services:
  backend:
    type: ClusterIP
    port: 8000
    targetPort: 8000

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod Security Context
podSecurityContext:
  fsGroup: 2000

# Container Security Context
securityContext: {}

# Pod annotations
podAnnotations: {}

# Image pull secrets
imagePullSecrets: []

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network Policies
networkPolicy:
  enabled: false

persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
