# Development environment values
replicaCount: 1

backend:
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

ingress:
  enabled: false

services:
  backend:
    type: NodePort
  frontend:
    type: NodePort

podDisruptionBudget:
  enabled: false
